# mgcarpet is free and takes no money. It requires the purchase of the
# original game, which is a sufficient cost.
#
# These are all the platforms on which I do not ask for money:

buy_me_a_coffee:
community_bridge:
custom:
github:
issuehunt:
ko_fi:
lfx_crowdfunding:
liberapay:
open_collective:
patreon:
polar:
thanks_dev:
tidelift:
