//! The authenticity-matrix config, in two layers.
//!
//! Project stance: the authentic original behavior is always the
//! default, and every modern enhancement is an opt-in flip.
//! Until a real in-game options screen exists, the flips live in:
//!
//! - **`mgcarpet.json.defaults`** — the default baseline, EVERY option
//!   spelled out. Generated by the app when missing and REGENERATED
//!   when its `_version` stamp is stale, so it doubles as the
//!   always-current option reference (do not hand-edit — it will be
//!   overwritten on schema bumps; overrides go in the overlay).
//! - **`mgcarpet.json`** — optional, sparse: only the options you want
//!   to override, same structure as the defaults file. The in-game
//!   options menu persists its changes here.
//!
//! CLI flags override both for one run. Unknown fields are ignored
//! (older binaries tolerate newer configs).
//!
//! # Taxonomy
//!
//! Options are grouped first by **domain** (where they act) and, within
//! a domain, by **class** (how faithful they are). The domains:
//!
//! - **`sim`** — feeds the deterministic world model / the state-hash
//!   goldens. Any non-default here means the run is not a faithful
//!   fixture. Split into tunable `parameters` and discrete `options`.
//! - **`render`** — presentation only, never touches the sim.
//!   `enhancement` = fair visual/info opt-ins; `debug` = dev overlays
//!   that visualise the real sim (not for normal play).
//! - **`controls`** — input devices. `preferences` = neutral bindings/
//!   sensitivity; `models` = the flight-control tiers.
//! - **`audio`** — banks, voiceover, volumes. All faithful preferences.
//! - **`gameplay`** — `enhancement` = fair play opt-ins; `cheat` =
//!   otherwise-impossible power (invulnerability, all spells).
//! - **`dev`** — pure troubleshooting instruments, never gameplay.
//!
//! ```json
//! { "render": { "enhancement": { "smooth_shading": true } } }
//! ```

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Default config file name, looked up in the working directory. The
/// defaults layer lives beside it as `<name>.defaults`.
pub const DEFAULT_PATH: &str = "mgcarpet.json";

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Options that feed the deterministic world model (state-hash
    /// critical — any non-default here breaks faithful fixtures).
    pub sim: SimConfig,
    /// Presentation options — never touch the sim.
    pub render: RenderConfig,
    /// Input-device options: bindings, sensitivity, flight-control tiers.
    pub controls: ControlsConfig,
    /// Audio preferences.
    pub audio: AudioConfig,
    /// Play-affecting options: fair enhancements and power cheats.
    pub gameplay: GameplayConfig,
    /// Development/troubleshooting instruments.
    pub dev: DevConfig,
    /// Where the original game installs live, for the first-run /
    /// stale-epoch auto-bake (src/bakecheck.rs). Unset = `MGC_GAMEDATA`
    /// or `gamedata/` in the working directory. A system path, outside
    /// the option taxonomy.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gamedata: Option<PathBuf>,
}

// ===========================================================================
// sim — deterministic world model (fidelity-critical)
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimConfig {
    /// Tunable numeric parameters.
    pub parameters: SimParameters,
    /// Discrete sim choices.
    pub options: SimOptions,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimParameters {
    /// Entity-pool capacity override (G-class — a larger pool can carry
    /// a roster the original would have dropped, so a replay taped with
    /// it enlarged is not a faithful fixture). `None` = the per-game
    /// faithful chassis default (`ChassisParams`, 1000 both games).
    /// Also settable for one run with `--pool-slots N` (2..=60000).
    pub entity_pool_size: Option<u32>,
    /// Creature wake-radius override in TILES (G-class, like the
    /// pool). `None` = the faithful 24 tiles (both retail engines,
    /// gate 0x240_0000 dist²); `Some(0)` = always awake (sleep was a
    /// period CPU optimization — asleep creatures still move but
    /// don't scan, take mail damage, or re-derive segment spacing;
    /// disabling it condenses dragons at range and applies ranged
    /// damage immediately). Also settable with `--awake-range N`
    /// (0 = off/always awake).
    pub awake_range: Option<u32>,
}

/// Discrete sim options.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimOptions {
    /// Game speed — the retail F3 option. Retail implements it as a
    /// sim-step multiplier (the entity-update tick runs N times per
    /// rendered frame: remc1 :41672, remc2 EF:31800); our fixed-Hz
    /// loop expresses the same thing by scaling the tick accumulator.
    /// Hash-neutral: every tick is bit-identical, only the wall-clock
    /// pacing changes. Toggle at runtime with F3 (retail's key).
    /// Session-only: resets to Normal at every level entry and is
    /// never persisted — a situational control (waiting out balloon
    /// mana runs), not a standing preference.
    pub game_speed: GameSpeed,
}

/// The game-speed levels. Retail ships THREE (MC1 :20123 `%= 3`,
/// Normal/Fast/Very Fast at 1×/4×/16× sim steps per frame — remc1
/// :41672; MC2 tops out at 8×, EF:31800); `slow` is our addition
/// (deliberate: no retail equivalent).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GameSpeed {
    /// Half speed — ours, for sightseeing/accessibility (no retail
    /// equivalent; retail's slowest is normal).
    Slow,
    /// The authentic pace (24 sim ticks per second).
    #[default]
    Normal,
    /// Retail Fast: 4× (both games run 4 sim steps per frame).
    Fast,
    /// Retail's top speed — game-keyed like retail: MC1 "Very Fast"
    /// = 16×, MC2 "Super Fast" = 8×.
    VeryFast,
}

impl GameSpeed {
    /// The wall-clock multiplier on the sim tick rate.
    pub fn multiplier(self, is_mc2: bool) -> f32 {
        match self {
            GameSpeed::Slow => 0.5,
            GameSpeed::Normal => 1.0,
            GameSpeed::Fast => 4.0,
            GameSpeed::VeryFast => {
                if is_mc2 {
                    8.0
                } else {
                    16.0
                }
            }
        }
    }

    /// F3 cycles slow → normal → fast → very-fast → slow (retail F3
    /// cycles its three; ours includes the slow addition).
    pub fn cycle(self) -> Self {
        match self {
            GameSpeed::Slow => GameSpeed::Normal,
            GameSpeed::Normal => GameSpeed::Fast,
            GameSpeed::Fast => GameSpeed::VeryFast,
            GameSpeed::VeryFast => GameSpeed::Slow,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            GameSpeed::Slow => "slow (0.5x)",
            GameSpeed::Normal => "normal (1x)",
            GameSpeed::Fast => "fast (4x)",
            GameSpeed::VeryFast => "very fast (MC1 16x / MC2 8x)",
        }
    }

    /// The in-game toast form — no parentheticals (the F3 echo line).
    pub fn toast_label(self) -> &'static str {
        match self {
            GameSpeed::Slow => "slow",
            GameSpeed::Normal => "normal",
            GameSpeed::Fast => "fast",
            GameSpeed::VeryFast => "very fast",
        }
    }
}

// ===========================================================================
// render — presentation only
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderConfig {
    /// Neutral visual preferences (fidelity-free knobs).
    pub preference: RenderPreference,
    /// Fair visual/informational opt-ins.
    pub enhancement: RenderEnhancement,
    /// Dev overlays that visualise the real sim — not for normal play.
    pub debug: RenderDebug,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderPreference {
    /// The aim crosshair (toggle at runtime with C): a white-edged
    /// black cross at the TRUE aim point. Gameplay aim cursor, ON by
    /// default — both retails steered by a live on-screen cursor, and
    /// the enhanced chase-the-pointer steering is unreadable without
    /// it (the crosshair IS the desired heading). Split 2026-07-23
    /// from the autoaim lock markers, which stay a debug instrument
    /// (`render.debug.autoaim_hints`).
    pub crosshair: bool,
    /// The textured parallax sky (retail's Sky option, on by
    /// default): the per-environment 256x256 cloud plane scrolled by
    /// yaw (4 wraps per revolution), slid by pitch, rolled with the
    /// bank. Off = the flat horizon-color fill (retail's sky-off
    /// keyColor). Caves never have one, exactly like retail.
    pub sky: bool,
    /// Water reflections (retail's Reflections option, on by
    /// default): sea tiles mirror the landscape about the water
    /// plane, wobbling with the wave (remc2 GRO:1104-1431 — terrain
    /// only, never sprites; our planar-mirror pass works from any
    /// altitude where retail cut off when flying high). Off = the
    /// plain animated water.
    pub reflections: bool,
    /// Dynamic light sources (retail MC2's Dynamic Lighting option,
    /// on by default): fireballs, explosions and standing fire cast
    /// a sphere of light that brightens the terrain around them —
    /// Night/Cave levels only, exactly retail's gate (remc2
    /// AddEvent2_847D0: day tables invert, added shade rows would
    /// darken). Terrain only, like retail — sprites are never lit.
    pub light_sources: bool,
    /// Fog view distance in TILES — where the distance fog fully
    /// occludes (the fade band runs 0.75·D..0.95·D, retail's hardcoded
    /// 15..19-tile ramp scaled). 20 = the retail constants (remc2
    /// GRO:668-679) — a pure period-performance choice that also
    /// deliberately overlaps the monster sight/acquisition radii
    /// (15-20 tiles) so pop-in hides in the fog; raising it reveals
    /// creatures acting before you can see them. Beyond the wall the
    /// terrain lingers as flat horizon silhouettes that always melt
    /// into the sky across the fixed 95..125-tile band (terrain.wgsl
    /// EXT_START..EXT_END), hiding the torus wrap unconditionally —
    /// and the fog may never reach into that band: values clamp to
    /// [`MAX_FOG_TILES`] = 90 at load, CLI and in the renderer (the
    /// old 255 whole-torus stop is retired; player-ruled 2026-08-08).
    /// 0 = fog off (the melt still runs). DEFAULT 50 (deliberate:
    /// retail's 20 was performance-only); the menu offers the stops
    /// 20 (faithful) / 50 (default) / 70 (high) / 90 (max).
    pub fog_distance: u32,
    /// Vertical sync (on by default — off has no visual upside, only
    /// tearing). Off releases the frame rate from the display's
    /// refresh so the `fps` debug overlay can measure what the
    /// machine actually renders — the effect-cost measuring rig. A
    /// display device preference: no retail analogue (DOS VGA
    /// page-flipped at whatever rate the frame took), so fidelity-free
    /// by construction.
    pub vsync: bool,
    /// Borderless fullscreen (Alt+Enter, the classic toggle). DEFAULTS
    /// ON: the originals ran one exclusive full-screen video mode and
    /// offered no window, so fullscreen is the faithful presentation as
    /// well as the one people want. The
    /// window drops its decorations and covers the monitor the window
    /// currently sits on — a BORDERLESS window, never an exclusive
    /// video-mode change: no mode switch, no black-screen flicker, and
    /// alt-tab stays instant. The desktop's own resolution is used, so
    /// the presentation aspect is whatever the monitor is; the HUD
    /// layout law (`ui::HudFrame`) anchors the panels to the screen
    /// edges instead of stretching them. A display-device preference
    /// with no retail analogue (DOS was 320×200/640×480 exclusive),
    /// hence Preference — fidelity-free either way.
    pub fullscreen: bool,
    /// Play the full-screen FMV movies (intro, MC2 cutscenes, outro).
    /// ON is the faithful setting — retail plays them and offers no
    /// way to turn them off; the switch exists because a 3165-frame
    /// intro wears thin on replay, and any key skips the chain in any
    /// case. Off is a Preference, not a fidelity gap: nothing in the
    /// simulation reads it.
    pub movies: bool,
    /// Edge smoothing for the 3D view. See [`AntiAliasing`].
    ///
    /// No retail analogue — DOS drew one 320x200 buffer and filtered
    /// nothing — so it is fidelity-free, a display knob like vsync.
    pub anti_aliasing: AntiAliasing,
    /// Show the movies' subtitle lines.
    ///
    /// Retail gates these on LANGUAGE and sound, not on taste: the
    /// narration is recorded in English only, so both games turn
    /// subtitles on for every non-English build, and for English only
    /// when there is no digital-sound device (remc1
    /// `sub_357C0_35B80`; remc2 MenusAndIntros.cpp:756-765). An
    /// English install with working sound — which is what this port
    /// runs — therefore shows NONE, and hears the narration instead.
    /// OFF is that faithful reading; ON forces the strip open, which
    /// also lifts the picture the way retail does to make room.
    pub movie_subtitles: bool,
    /// The in-view rival wizard name + health-bar tags. See
    /// [`RivalTags`].
    pub rival_tags: RivalTags,
}

/// How the 3D view's jagged edges are smoothed.
///
/// The two techniques are not interchangeable here, because most of
/// this engine's visible stair-stepping is NOT triangle edges. Every
/// creature, tree and building is a quad whose silhouette comes from
/// discarding palette index 0 — hard 1-bit transparency, nearest
/// sampled. MSAA runs the fragment shader once per fragment and a
/// discard kills all of that fragment's samples, so those silhouettes
/// come out exactly as aliased as they went in; what it does smooth is
/// true geometry, chiefly the terrain against the sky. Supersampling
/// re-evaluates the discard at a higher resolution, so it is the only
/// one that reaches the sprites — at the cost of the whole frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AntiAliasing {
    Off,
    /// 4x multisampling: cheap, smooths terrain silhouettes only.
    /// Baked into the render pipelines, so it needs a restart.
    Msaa,
    /// Supersample the whole frame at 1.5x (2.25x the pixels).
    Ssaa15,
    /// Supersample at 2x (4x the pixels).
    Ssaa2,
}

impl AntiAliasing {
    /// MSAA sample count for the pipelines (1 = none).
    pub fn samples(self) -> u32 {
        match self {
            AntiAliasing::Msaa => 4,
            _ => 1,
        }
    }

    /// Supersampling factor (1.0 = none).
    pub fn render_scale(self) -> f32 {
        match self {
            AntiAliasing::Ssaa15 => 1.5,
            AntiAliasing::Ssaa2 => 2.0,
            _ => 1.0,
        }
    }
}

/// Fog view-distance cap, tiles (mgc_render::MAX_FOG_TILES twin):
/// keeps the whole fog band (full occlusion at 0.95·D) short of the
/// 95..125-tile silhouette melt band, which runs unconditionally and
/// hides the world's torus wrap. Applied at config load and to the
/// CLI override; 0 stays "fog off".
pub const MAX_FOG_TILES: u32 = 90;

/// The fog-distance menu stops: (tiles, tag). Top stop =
/// [`MAX_FOG_TILES`]; the old 255 whole-torus stop is retired
/// (player-ruled 2026-08-08: the fog must never reach the melt band).
pub const FOG_STOPS: [(u32, &str); 4] =
    [(20, "faithful"), (50, "default"), (70, "high"), (90, "max")];

impl Default for RenderPreference {
    fn default() -> Self {
        Self {
            crosshair: true,
            sky: true,
            reflections: true,
            light_sources: true,
            fog_distance: 50,
            vsync: true,
            fullscreen: true,
            movies: true,
            anti_aliasing: AntiAliasing::Off,
            movie_subtitles: false,
            rival_tags: RivalTags::default(),
        }
    }
}

/// The in-view rival wizard tag — the boxed name + health bar retail
/// MC2 floats over every visible rival wizard sprite
/// (`DrawSorcererNameAndHealthBar_2CB30`, remc2 GameRenderHD.cpp:2797,
/// hooked per drawn class-3 model-0/1 sprite at :5010-17). Retail MC2
/// ships it ON with a "Player Names" toggle (PlayerInput.cpp:1503);
/// retail MC1 has no such tag at all.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RivalTags {
    /// Each game's faithful surface: MC2 tags every visible rival,
    /// MC1 tags nothing. The authentic default.
    #[default]
    Auto,
    /// Tags in both games — brings the MC2 tag to MC1 as an opt-in
    /// (deliberate; the bars are simply too useful to leave behind).
    On,
    /// No tags anywhere — retail MC2's "Player Names Off".
    Off,
}

impl RivalTags {
    /// Whether tags draw for the running game.
    pub fn resolve(self, is_mc2: bool) -> bool {
        match self {
            RivalTags::Auto => is_mc2,
            RivalTags::On => true,
            RivalTags::Off => false,
        }
    }
}

/// The fire look: `classic` = whatever the running game draws normally
/// (the retail fire/explosion sprites, untouched); `enhanced` = the
/// procedural fire — fireball flame + comet trail (the core sprite is
/// hidden under it), the meteor crater's two-wave flame walls with
/// lingering smoke, and the detaching shockwave ring. Presentation
/// only: the sim never changes, whichever is selected. Classic is the
/// default for now — pending broader playtesting before enhanced
/// earns default-on status.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FireEffects {
    #[default]
    Classic,
    Enhanced,
}

/// Lightning look: retail's sprite-216 zigzag flash vs the procedural
/// bolt — a fractal main channel with side branches, a leader →
/// return-stroke → decay envelope per strike, successive strikes
/// overlapping into a continuous stream. Presentation only: the sim
/// (trail-node entities, blasts, damage) is identical whichever is
/// selected. Classic is the default — pending playtesting, like fire.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LightningEffects {
    #[default]
    Classic,
    Enhanced,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderEnhancement {
    /// Interpolate terrain shade across tile centers instead of the
    /// original's one shade level per tile (toggle at runtime with T).
    /// DEFAULTS ON (deliberate default-on deviation) — toggle off for
    /// the per-tile retail look.
    pub smooth_shading: bool,
    /// Entities render interpolated between the last two sim ticks —
    /// the camera's one-tick lerp timeline extended to the world —
    /// so movement is frame-smooth at any fps instead of stepping at
    /// tick rate (rapid-fire streams stop looking stationary).
    /// Presentation only: the sim is untouched, poses pair across
    /// snapshots by (slot, generation), teleports snap. DEFAULTS ON
    /// (deliberate default-on deviation) — toggle off in the menu for
    /// the tick-stepped retail look.
    pub smooth_motion: bool,
    /// HUD transparency (the top-strip panels + radar blend over the
    /// sky). MC1 always draws the HUD translucent; MC2 adds a toggle
    /// (Shift+F6, "Panel Transparency") to make it opaque for
    /// readability (the radar especially). A plain on/off preference —
    /// faithfulness is deliberately not scored here; DEFAULT OFF (opaque,
    /// the readable choice — transparency makes the radar map less
    /// useful). Legacy config strings `mc1`/`opaque` still parse.
    pub hud_transparency: HudTransparency,
    /// Highlight claimed/possessed dwellings on the overhead map in
    /// the owner's color — MC2's map behavior brought to MC1 as an
    /// opt-in (deliberate; P-class; MC1 never marks houses).
    pub map_owned_buildings: bool,
    /// Tag every pickable spell jar with its granted spell's icon —
    /// on the overhead map (a small icon stamp over the jar dot) and
    /// floating over the jar in the main view. P-class level-scouting
    /// instrument (the original never labels jars; you learn by flying
    /// through). Covers MC1's class-12 jars (red AND blue) and MC2's
    /// class-15 spell tokens.
    pub expose_jar_spells: bool,
    /// Overhead-map marker size multiplier (dots AND icon stamps,
    /// both map surfaces). 1.0 = the shipped baseline (deliberate;
    /// retail's markers are surface-pixel-scale, near-invisible at
    /// modern resolutions — there is no faithful size to anchor to).
    /// Any other value switches entity dots to screen-space quads
    /// whose size no longer varies with minimap zoom.
    pub map_marker_scale: f32,
    /// Swap selected overhead-map dots for miniature sprites of the
    /// thing itself (deliberate deviation): spell jars/tokens, and
    /// the dolmen/shrine/statue statics. The expose-jar-spells debug
    /// option outranks this for jars (its spell icon + red dot draw
    /// instead, never both). Families with no icon built keep their
    /// dots.
    pub map_marker_icons: bool,
    /// Fog the fullscreen map beyond the world's true extent
    /// (deliberate deviation): the world wraps toroidally, so the
    /// player-centered map repeats entities past ±half a world from
    /// the player — retail simply shows the duplicates. A soft black
    /// fade starting at the (heading-rotated) extent rectangle hides
    /// them; drawn over every map layer. The round minimap never
    /// shows duplicates (its zoom caps under half a world), so this
    /// covers only the map screens.
    pub map_extent_fog: bool,
    /// Procedural fire (fireball flame/trail, meteor crater walls +
    /// smoke, shockwave) vs the retail sprites. Defaults to classic
    /// for now. Needs smooth_motion for the frame-rate flame; with
    /// smooth_motion off the classic sprites draw regardless.
    pub fire: FireEffects,
    /// Procedural lightning (fractal branched bolt with a strike
    /// envelope) vs the retail zigzag flash sprites. Defaults to
    /// classic. Needs smooth_motion like fire.
    pub lightning: LightningEffects,
}

impl Default for RenderEnhancement {
    fn default() -> Self {
        Self {
            smooth_shading: true,
            smooth_motion: true,
            hud_transparency: HudTransparency::default(),
            map_owned_buildings: false,
            expose_jar_spells: false,
            map_marker_scale: 1.0,
            map_marker_icons: false,
            map_extent_fog: false,
            fire: FireEffects::default(),
            lightning: LightningEffects::default(),
        }
    }
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderDebug {
    /// Red-on-black health bars floating above monsters (toggle at
    /// runtime with H). The original never shows creature life — the
    /// combat-system debugging instrument.
    pub health_bars: bool,
    /// The autoaim lock markers: per-hand markers — left `+`, right
    /// `×`, blinking red — on the target each hand's equipped spell
    /// would acquire this instant. A crude, strictly-functional
    /// projectile-behavior predictor (pure preview: no sim writes, no
    /// RNG); the original shows no such UI. Acquisition ≠ hit (homing
    /// is capped 5/tick yaw). Split 2026-07-23 from the plain aim
    /// crosshair, which is now the `render.preference.crosshair`
    /// gameplay cursor. Deliberately NO serde alias for the legacy
    /// `crosshair` key: the menu-persist path MERGES into the
    /// existing mgcarpet.json, so a migrated file holds BOTH keys and
    /// an alias makes that a "duplicate field" load error. The stale
    /// key is simply ignored.
    pub autoaim_hints: bool,
    /// Overlay live trigger volumes / portals on the overhead map as
    /// tinted circles (toggle at runtime with V). The original never
    /// reveals trigger areas — this is a sanctioned deviation, and the
    /// event-system debugging instrument.
    pub map_trigger_areas: bool,
    /// The spawn-grace shimmer: a thin bottom-center strip draining
    /// with the respawn invulnerability window. Retail shows NOTHING
    /// for grace, so this is a debug cue and defaults OFF (faithful: no
    /// grace indicator at all).
    pub grace_meter: bool,
    /// The FPS overlay: frame rate + frame time in the bottom-right
    /// corner, refreshed twice a second. The performance measuring
    /// instrument (gauge what each non-faithful effect costs) — pair
    /// with `vsync` off to read the machine's real headroom instead of
    /// the display refresh.
    pub fps: bool,
    /// The coordinate overlay (toggle at runtime with K): carpet
    /// position in engine units in the bottom-LEFT corner — "x N,
    /// y N, z N (+E)" where z is the altitude and (+E) the elevation
    /// over the terrain underneath. The flight/altitude debugging
    /// instrument (the desired-altitude band language IS engine
    /// units: clearance 128/256, band 1024/3072).
    pub coords: bool,
    /// The entity-pool overlay: "ents used/capacity" on its own fixed
    /// line above the coordinate readout (bottom-left). In-use counts
    /// every allocated pool slot including not-yet-reaped corpses —
    /// the entity-pressure diagnosis instrument (effect leaks,
    /// pool-exhaustion anomalies).
    pub entities: bool,
}

// ===========================================================================
// controls — input devices
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlsConfig {
    /// Neutral input preferences (bindings, sensitivity, axis).
    pub preferences: ControlPreferences,
    /// The flight-control tiers.
    pub models: ControlModels,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlPreferences {
    /// Key-binding profile. P-class, input mapping ahead of the
    /// `FlightInput` seam.
    pub bindings: Bindings,
    /// Mouse-to-stick / mouse-look sensitivity multiplier (P-class
    /// preference, 1.0 = default).
    pub mouse_sensitivity: f32,
    /// Per-axis fractions of the general sensitivity, 0.0..=1.0
    /// (shown as 0–100%). X (horizontal/turn) DEFAULTS TO HALF —
    /// player ruling 2026-07-23: full-rate X saturates the enhanced
    /// turn damper into an all-or-nothing feel; half stretches it
    /// back into a fluid range. Y (vertical/aim) defaults to full.
    pub mouse_sensitivity_x: f32,
    pub mouse_sensitivity_y: f32,
    /// Invert the mouse Y axis. `invert_y = true` means mouse-up/forward
    /// = nose DOWN (dive), like a flight stick — the polarity BOTH
    /// originals ship — and it is the DEFAULT. `false` = mouse-up = nose
    /// up (the FPS convention). Pure preference.
    pub invert_y: bool,
    /// The retail MC2 "Flight Assistance" option (options-menu case
    /// 5 flips `byte_0x36DEA_fly_asistant`; the idle auto-center in
    /// `sub_1A7A0` is gated on it, PI:1988): with the mouse untouched
    /// and no action for 0x30 polls the stick recenters. Applies to
    /// the faithful control model only. DEFAULT OFF (off is MC2's retail
    /// default; MC1 never had it). Legacy config strings `auto`/`off`
    /// both parse as off.
    pub fly_assistant: FlyAssistant,
}

impl Default for ControlPreferences {
    fn default() -> Self {
        Self {
            bindings: Bindings::default(),
            mouse_sensitivity: 1.0,
            mouse_sensitivity_x: 0.5,
            mouse_sensitivity_y: 1.0,
            invert_y: true,
            fly_assistant: FlyAssistant::default(),
        }
    }
}

/// The fly-assistant idle auto-center: plain on/off, default off —
/// MC2's retail default, and MC1 never had the option (legacy
/// game-keyed `auto` configs parse as off).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FlyAssistant {
    /// The assistant everywhere (in MC1/HW an enhancement pairing
    /// with the Backspace full stop — retail MC1 relied on the
    /// visible DOS cursor for manual centering; we have no cursor, so
    /// a resting stick offset drifts. Toggle on to trade authenticity
    /// for stability).
    On,
    /// No auto-center — parked-deflection handling everywhere
    /// (hands-free orbiting; you trim your own drift).
    #[default]
    #[serde(alias = "auto")]
    Off,
}

impl FlyAssistant {
    pub fn on(self) -> bool {
        matches!(self, FlyAssistant::On)
    }
}

/// The flight-control tiers: two ORTHOGONAL enums, freely combinable,
/// authentic values as defaults. Enums rather than booleans by design
/// (room for named alternates like `mc2` or `torso-aim` later).
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlModels {
    /// Thrust + steering model. G-CLASS (physics — a replay taped
    /// under `enhanced` is not a faithful fixture).
    pub thrust: ThrustModel,
    /// Altitude model. G-CLASS. Extended lift adds explicit float
    /// up/down keys (no original equivalent); it never bypasses wall
    /// blocking and float-up is capped at the level's highest terrain.
    pub altitude: AltitudeModel,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ThrustModel {
    /// The faithful thrust law (byte-identical in BOTH games: throttle
    /// step 16 clamped ±80 with no release decay, strafe ±16/clamp 80/
    /// decay −4, rate-based mouse steering (offset = turn RATE, like
    /// an airplane stick), thrust always in the level ground plane
    /// regardless of aim pitch; remc1 sub_main.cpp:55110-835 ≡ remc2
    /// EF:59635-51). The sim still dispatches the faithful per-game
    /// MOVER underneath (MC2 worlds get move_mc2's vertical/collision
    /// differences) — "classic" names the control law tier.
    #[default]
    #[serde(alias = "mc1")]
    Classic,
    /// Hold-to-fly with automatic deceleration on release (keeps the
    /// authentic level-plane thrust rule). Steering is
    /// chase-the-pointer: the mouse moves the aim crosshair (a
    /// desired heading, kept on-screen) and the carpet turns to
    /// chase it with an ease-out curve; casts fire along the
    /// crosshair. The camera banks proportionally to turn rate ×
    /// forward speed (never when standing or strafing), unlike
    /// retail's fixed bank.
    Enhanced,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AltitudeModel {
    /// Terrain-follow only: the carpet floats up along rising ground
    /// (hard floor ground+128) and settles by itself; no fly-up
    /// control exists (remc1 sub_455D0 vertical rules).
    #[default]
    #[serde(alias = "faithful")]
    Classic,
    /// The desired-altitude law: E/Q pin a GROUND-RELATIVE desired
    /// altitude (fast steps at the classic full-pitch climb rate);
    /// the carpet drifts toward it at the game's standard descent
    /// speed, follows terrain at that offset, and recovers from any
    /// bump or fling. Capped at the per-game climb band (4 tiles
    /// over terrain; MC2 caves higher), wall blocking and the cave
    /// roof fully intact.
    #[serde(alias = "extended-lift")]
    Enhanced,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Bindings {
    /// The original scheme: mouse aims, Up/Down arrows accelerate/
    /// decelerate, Left/Right arrows strafe.
    #[default]
    Classic,
    /// W/S thrust, A/D strafe, mouse aims (arrows keep turn/pitch in
    /// the enhanced thrust model).
    Wasd,
}

// ===========================================================================
// audio — faithful preferences
// ===========================================================================

/// Audio preferences. Volumes are plain preference, not authenticity
/// flips; the MIXER selection (faithful tile-rule vs enhanced
/// distance-weighted emitters) will join `render`/`gameplay` when the
/// enhanced mixer exists — only the faithful port is implemented.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AudioConfig {
    /// Sample playback (F1 toggles at runtime, the original's key).
    pub sound: bool,
    /// Music playback (F2 toggles at runtime, the original's key).
    pub music: bool,
    /// Master gains, 0..=1 linear.
    pub sfx_volume: f32,
    pub music_volume: f32,
    /// Which MC1 music arrangement plays (multi-column matrix option —
    /// all three shipped on the CD as per-sound-card targets, so each
    /// column is authentic; MC2's XMI gameplay music is unaffected).
    pub arrangement: MusicArrangement,
    /// MC2 objective voiceovers (the redbook speech clips) — the
    /// original's in-game "Speech On/Off" toggle
    /// (`OptionsSettingFlag & 0x40`, remc2 PlayerInput.cpp:1221).
    pub speech: bool,
    /// Narration subtitles: the ETEXT sentence behind each objective
    /// voiceover, drawn as a top-of-screen overtitle when the cue
    /// fires. (Retail MC2 shows this text only INSTEAD of audio — the
    /// objective textbox is its speech-off/no-CD fallback,
    /// DrawCurrentObjectiveTextbox_30630; our `on` overtitles the
    /// voiceover too.) On/off, default on.
    pub subtitles: Subtitles,
}

impl Default for AudioConfig {
    fn default() -> Self {
        AudioConfig {
            sound: true,
            music: true,
            sfx_volume: 1.0,
            music_volume: 1.0,
            arrangement: MusicArrangement::default(),
            speech: true,
            subtitles: Subtitles::default(),
        }
    }
}

/// When narration subtitles show (see [`AudioConfig::subtitles`]).
/// Plain on/off (legacy `auto` configs parse as `on`).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Subtitles {
    /// Subtitle every narration, voiceover or not (the accessibility
    /// overtitle). The default.
    #[default]
    #[serde(alias = "auto")]
    On,
    /// Never (retail with speech on shows no text either way).
    Off,
}

impl Subtitles {
    pub fn on(self) -> bool {
        matches!(self, Subtitles::On)
    }
}

/// MC1 shipped three interchangeable music arrangements, one per
/// sound-card family (`MUSIC<bank>-<digit>`, remc1 :54029-30): AdLib
/// FM (digit 0), Roland MT-32 (1, not baked — no MT-32 renderer), and
/// General MIDI (2). The bundle always carries the FM render; the GM
/// render (the pure-Rust oxisynth + a GM soundfont, `crate::synth`) is
/// baked when a soundfont is present — the game ships one, so GM is the
/// out-of-the-box default on every platform.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MusicArrangement {
    /// The best-available render: General MIDI when the bundle
    /// carries it, else the FM render.
    #[default]
    Auto,
    /// Force the AdLib FM (OPL3) render — the `-0` driver's sound.
    Fm,
    /// Force the General MIDI render (falls back to FM with a console
    /// note when the bundle has no GM tracks — the shipped soundfont was
    /// missing at bake time; drop one in or set `MGC_SOUNDFONT` and
    /// rebake).
    Gm,
}

impl MusicArrangement {
    /// Resolve to the runtime preference bit ([`mgc_audio::Audio`]
    /// falls back to FM per track when GM is absent).
    pub fn prefer_gm(self) -> bool {
        !matches!(self, MusicArrangement::Fm)
    }
}

// ===========================================================================
// gameplay — play-affecting opt-ins and cheats
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayConfig {
    /// Fair play opt-ins (still authentic-legal — no impossible power).
    pub enhancement: GameplayEnhancement,
    /// Retail-bug patches: things retail messes up that the port can
    /// do better — every deliberate upstream bugfix, with BOTH arms
    /// implemented. Faithful fixtures are protected structurally:
    /// goldens, unit tests and mgc-conform build worlds that default
    /// to the retail arms, and `--record`/`--replay` force them.
    pub patches: GameplayPatches,
    /// Cheats: otherwise-impossible power. Any of these on = a
    /// non-canonical run.
    pub cheat: GameplayCheat,
}

/// One retail-bug patch's arm. `retail` = the shipped bug, bug for
/// bug; `patched` = the fix. (Aliases `off`/`on` accepted.)
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PatchArm {
    /// Retail's shipped behavior, bug for bug.
    #[default]
    #[serde(alias = "off")]
    Retail,
    /// The port's fix.
    #[serde(alias = "on", alias = "fixed")]
    Patched,
}

impl PatchArm {
    pub fn on(self) -> bool {
        self == PatchArm::Patched
    }
    pub fn from_on(on: bool) -> Self {
        if on {
            PatchArm::Patched
        } else {
            PatchArm::Retail
        }
    }
}

/// The `gameplay · patches` class (docs/DEVIATIONS.md "Patch
/// options"): each field picks one arm of a deliberate upstream
/// bugfix. All are Live options with no hotkeys; sim-affecting ones
/// never leak into faithful fixtures (see [`GameplayConfig::patches`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayPatches {
    /// Create Castle pricing after castle loss (all 3 games).
    /// `retail` (DEFAULT — player-ruled 2026-08-08): the stale cost
    /// stamp; after your castle dies the recast costs the last
    /// stamped ladder price (the first-castle lockout — possibly a
    /// deliberate period challenge). `patched`: live-law pricing; a
    /// fresh castle is always affordable (1000) when homeless.
    pub castle_recast_cost: PatchArm,
    /// Spell jars re-snap to the ground every tick. Retail's terrain
    /// reshaping leaves jars buried (HW ships several!) or floating.
    pub jar_ground_snap: PatchArm,
    /// Settled MC1 mana balls track the ground. Retail freezes a ball
    /// wherever its settle budget expired — mid-hop balls hang in the
    /// air forever; terrain edits bury grounded ones.
    pub ball_ground_track: PatchArm,
    /// MC1 mana balls roll downhill map-wide. Retail only rolls balls
    /// within 24 tiles of you (a period perf save), so approaching
    /// mana visibly "runs away downhill". Balls only — creature
    /// wake-up is untouched.
    pub map_wide_ball_rolling: PatchArm,
    /// A possessed dwelling keeps its true footprint. Retail's
    /// owner-flag stamp shrinks it to the flag sprite, so villagers
    /// and defenders spawn walled-in ON the roof and their corpse
    /// flames destroy the house you just possessed.
    pub possessed_footprint: PatchArm,
    /// MC2 castle downgrade's 10% mana haircut, computed safely.
    /// Retail's i32 math overflows at the level-7 rung — a maxed
    /// castle downgrade RAISES its capacity and scatters nothing.
    pub mc2_downgrade_overflow: PatchArm,
    /// MC2 Magic Mine proximity trigger. Retail ships the spell dead —
    /// nothing ever arms the trigger, so a mine floats, expires and
    /// sinks without detonating on anyone.
    pub mc2_magic_mine: PatchArm,
    /// MC2 mana dwellers share the wraith's proximity concealment:
    /// they materialize only inside retail's own ~19-tile fog band —
    /// a slant-distance sphere, so climbing out of the band conceals
    /// too (player-ruled 2026-08-08: one shape for every concealed
    /// entity). Their covert mana-stealing design leaned on retail's
    /// very short draw distance; under the port's extended fog they
    /// stand exposed map-wide — safe long-range meteor targets.
    /// `retail` = always drawn (the authentic entity itself has no
    /// fade); presentation-only, hash-silent (the sim never reads
    /// it).
    pub mc2_dweller_invisibility: PatchArm,
    /// The second win movie (`levelw2`) plays its own orphaned score
    /// table (bank 7 `win2`). Retail points both win movies at one
    /// script, so `levelw2` plays scored with the wrong bank.
    pub win2_movie_score: PatchArm,
    /// MC1 Create Castle placement validation (the "latch bug",
    /// certified on the mc1l32 recording). Retail anchors the
    /// placement scan at the casting HAND — a steerable tile beside
    /// the carpet — and skips it entirely when the ball lands by
    /// terrain touchdown, so a wall-corner cast raises a castle
    /// inside a no-castle maze and carves its protected walls.
    /// `patched` (default): the scan anchors at the carpet and the
    /// landing always re-checks.
    pub castle_latch_bug: PatchArm,
}

impl Default for GameplayPatches {
    fn default() -> Self {
        Self {
            // Player-ruled 2026-08-08: the lockout ships as the
            // authentic default; the fix is the opt-in.
            castle_recast_cost: PatchArm::Retail,
            jar_ground_snap: PatchArm::Patched,
            ball_ground_track: PatchArm::Patched,
            map_wide_ball_rolling: PatchArm::Patched,
            possessed_footprint: PatchArm::Patched,
            mc2_downgrade_overflow: PatchArm::Patched,
            mc2_magic_mine: PatchArm::Patched,
            mc2_dweller_invisibility: PatchArm::Patched,
            win2_movie_score: PatchArm::Patched,
            castle_latch_bug: PatchArm::Patched,
        }
    }
}

impl GameplayPatches {
    /// Every patch on its retail arm — what `--record`, `--replay`
    /// and every faithful fixture runs.
    pub fn retail_all() -> Self {
        Self {
            castle_recast_cost: PatchArm::Retail,
            jar_ground_snap: PatchArm::Retail,
            ball_ground_track: PatchArm::Retail,
            map_wide_ball_rolling: PatchArm::Retail,
            possessed_footprint: PatchArm::Retail,
            mc2_downgrade_overflow: PatchArm::Retail,
            mc2_magic_mine: PatchArm::Retail,
            mc2_dweller_invisibility: PatchArm::Retail,
            win2_movie_score: PatchArm::Retail,
            castle_latch_bug: PatchArm::Retail,
        }
    }

    /// The pre-option hard-wired behavior set: what native play ran
    /// before the patches became options. Port recordings taped
    /// before the header carried a patch policy replay under this
    /// (`map_wide_ball_rolling` did not exist then; the castle cost
    /// was live-law).
    pub fn legacy() -> Self {
        Self {
            castle_recast_cost: PatchArm::Patched,
            map_wide_ball_rolling: PatchArm::Retail,
            // Did not exist pre-option (2026-08-08): dwellers drew
            // plainly.
            mc2_dweller_invisibility: PatchArm::Retail,
            ..Self::default()
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayEnhancement {
    /// Which spell-selection interface is live (P-class, multi-column
    /// matrix option — interface only, the spell economy underneath is
    /// untouched). MC1's faithful surface = the fullscreen-map
    /// spellbook page; MC2's = the CTRL-hold docked selector pane
    /// (with the per-spell level sub-menus). `auto` (default) = each
    /// game's own faithful surface. MC1 accepts every value —
    /// including `mc2` (the pane replaces the map book; the map's
    /// book half becomes the stretched live view, MC2-style) and
    /// `mc1+mc2` (both surfaces at once). MC2 always resolves to the
    /// pane: a 26-spell book never had an in-map grid, so `mc1`/
    /// `mc1+mc2` coerce (with a console note) rather than invent one.
    pub spell_selector: SpellSelector,
    /// Remove any spell jar whose spell the local player already owns —
    /// and therefore can never pick up. Retail (BOTH MC1 and MC2)
    /// leaves such jars in the world forever (placed jars never decay),
    /// so they become permanent, unidentifiable clutter. An INTENTIONAL
    /// deviation from retail (deliberate; P-class): sweeps at level load
    /// AND the instant the player gains a spell. Single-player entity
    /// removal. Defaults ON — disable with `--no-prune-owned-jars` for a
    /// purist run. Covers MC1's class-12 jars and MC2's class-15 spell
    /// tokens. See docs/FIDELITY.md.
    pub prune_owned_jars: bool,
    /// Mouse-wheel spell cycling (the remc2/MC2HD idiom, no retail
    /// analogue): the wheel walks the LEFT button's cycle ring,
    /// SHIFT+wheel the RIGHT. Purely additive input — the faithful
    /// SHIFT/ALT+click rotation works either way — so it defaults ON;
    /// disable for a purist input surface.
    pub wheel_spells: bool,
}

impl Default for GameplayEnhancement {
    fn default() -> Self {
        Self {
            spell_selector: SpellSelector::default(),
            // Default-ON: removing jars you can never pick up. Purists
            // disable it with `--no-prune-owned-jars`.
            prune_owned_jars: true,
            // Default-ON: additive input, collides with nothing.
            wheel_spells: true,
        }
    }
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayCheat {
    /// All 24 spells granted + infinite mana (toggle at runtime with
    /// G). The spell-track playtest instrument; gameplay-affecting
    /// (G-class) — a replay taped with it on is not a faithful
    /// fixture. The original ships the equivalent debug commands
    /// ("access all spells" / "more mana", remc1's :48836 cheat menu).
    pub dev_spells: bool,
    /// Player invincibility — the pre-mortality dev behavior (damage
    /// totaled for display, never applied; no death). G-class
    /// playtest/accessibility instrument; the authentic default is
    /// MORTAL (grace window, castle respawn, castle-less death =
    /// level restart).
    pub invincible: bool,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SpellSelector {
    /// Each game's faithful surface: MC1 → the map-screen spellbook,
    /// MC2 → the CTRL pane. The authentic default.
    #[default]
    Auto,
    /// Force the MC1 map-screen spellbook (MC1 only; MC2 coerces to
    /// the pane).
    Mc1,
    /// Force the MC2 CTRL-hold selector pane; the map screen drops
    /// its spellbook half for the stretched live view.
    Mc2,
    /// Both surfaces at once (MC1 only): the map book stays AND the
    /// CTRL pane works everywhere — the no-compromise loadout.
    #[serde(rename = "mc1+mc2")]
    Mc1Mc2,
}

/// A [`SpellSelector`] resolved against the running game: which of the
/// two selection surfaces are live this session.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SelectorSurfaces {
    /// The MC1 map-screen spellbook page (its absence also switches
    /// the map screen's book half to the stretched live view).
    pub map_book: bool,
    /// The MC2 CTRL-hold docked selector pane.
    pub ctrl_pane: bool,
}

impl SpellSelector {
    /// Resolve for the running game. MC2 has exactly one shape (the
    /// pane); anything explicitly asking for the map book there is
    /// coerced, and the caller prints the note (so the message can
    /// name the config source).
    pub fn resolve(self, is_mc2: bool) -> SelectorSurfaces {
        if is_mc2 {
            return SelectorSurfaces {
                map_book: false,
                ctrl_pane: true,
            };
        }
        match self {
            SpellSelector::Auto | SpellSelector::Mc1 => SelectorSurfaces {
                map_book: true,
                ctrl_pane: false,
            },
            SpellSelector::Mc2 => SelectorSurfaces {
                map_book: false,
                ctrl_pane: true,
            },
            SpellSelector::Mc1Mc2 => SelectorSurfaces {
                map_book: true,
                ctrl_pane: true,
            },
        }
    }
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HudTransparency {
    /// Transparent: the whole HUD blends over the sky (MC1's always-on
    /// look, sub_23940's blend path). Legacy config value `mc1`.
    #[serde(alias = "mc1")]
    On,
    /// Opaque HUD (MC2's Panel Transparency toggle off): solid panels
    /// + radar, best readability. The default. Legacy value `opaque`.
    #[default]
    #[serde(alias = "opaque")]
    Off,
}

impl HudTransparency {
    pub fn transparent(self) -> bool {
        matches!(self, HudTransparency::On)
    }
}

// ===========================================================================
// dev — troubleshooting instruments
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct DevConfig {
    /// Seed the spellbook at level start with the spells a diligent
    /// player COULD legitimately hold entering this level — the union
    /// of every spell jar in the campaign levels before this one
    /// (MC1 only; see `campaign::plausible_spellbook`). Unlike
    /// `gameplay.cheat.dev_spells` this respects the campaign's spell
    /// economy (it never grants a spell the campaign couldn't have
    /// delivered yet), so bugs found while playtesting an individual
    /// level are real. G-class playtest instrument — NOT campaign
    /// state; a level so launched is not a faithful fixture. Grants on
    /// top of whatever the world already gave (starting spells etc.).
    pub plausible_spellbook: bool,
    /// Unclamp the enhanced-altitude band: q/e may pin the desired
    /// altitude anywhere up to the GLOBAL lift ceiling (the level's
    /// highest terrain + the 4-tile soft-ceiling margin) instead of
    /// the per-game ground-relative band (1024/3072 over terrain).
    /// The altitude-system inspection instrument from the original
    /// enhanced-flight spec; live-applied, never a faithful fixture.
    pub lift_unclamped: bool,
}

// ===========================================================================
// two-layer load
// ===========================================================================

impl Config {
    /// Load the two layers: `<path>.defaults` (generated when missing;
    /// the faithful baseline) deep-merged under `path` (optional,
    /// sparse overrides). When `explicit` is false (the default path),
    /// a missing override file simply yields the baseline; a path the
    /// user asked for must exist. Malformed JSON is always an error —
    /// better loud than silently authentic.
    pub fn load(path: &Path, explicit: bool) -> Result<Self, String> {
        let defaults_path = defaults_path(path);
        ensure_defaults(&defaults_path)?;

        let mut merged = match std::fs::read_to_string(&defaults_path) {
            Ok(text) => serde_json::from_str::<serde_json::Value>(&text)
                .map_err(|e| format!("{}: {e}", defaults_path.display()))?,
            Err(_) => serde_json::Value::Object(Default::default()),
        };
        match std::fs::read_to_string(path) {
            Ok(text) => {
                let overlay = serde_json::from_str::<serde_json::Value>(&text)
                    .map_err(|e| format!("{}: {e}", path.display()))?;
                merge(&mut merged, overlay);
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound && !explicit => {}
            Err(e) => return Err(format!("{}: {e}", path.display())),
        }
        let mut cfg: Self =
            serde_json::from_value(merged).map_err(|e| format!("{}: {e}", path.display()))?;
        // Cap the fog distance (old configs may carry the retired
        // 100/255 stops): the fog band must never reach the terrain
        // silhouette melt band. 0 stays "fog off".
        cfg.render.preference.fog_distance = cfg.render.preference.fog_distance.min(MAX_FOG_TILES);
        Ok(cfg)
    }
}

fn defaults_path(path: &Path) -> PathBuf {
    let mut os = path.as_os_str().to_owned();
    os.push(".defaults");
    PathBuf::from(os)
}

/// Deep-merge `overlay` into `base`: objects merge key-wise, everything
/// else is replaced by the overlay value.
fn merge(base: &mut serde_json::Value, overlay: serde_json::Value) {
    match (base, overlay) {
        (serde_json::Value::Object(b), serde_json::Value::Object(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(slot) => merge(slot, v),
                    None => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (b, o) => *b = o,
    }
}

/// The defaults-file schema stamp: bump whenever an option is added,
/// renamed, retyped or its default changes, so stale generated
/// baselines regenerate instead of feeding outdated values/shapes
/// into the merge.
const DEFAULTS_VERSION: u64 = 23;

/// Generate the defaults baseline so every option is spelled out and
/// discoverable. Regenerates automatically when its `_version` stamp
/// is missing or stale (the file is generated output — overrides
/// belong in `mgcarpet.json`).
fn ensure_defaults(path: &Path) -> Result<(), String> {
    if let Ok(text) = std::fs::read_to_string(path) {
        let current = serde_json::from_str::<serde_json::Value>(&text)
            .ok()
            .and_then(|v| v.get("_version").and_then(|n| n.as_u64()));
        if current == Some(DEFAULTS_VERSION) {
            return Ok(());
        }
        println!(
            "config: {} is from an older mgcarpet — regenerating (overrides in {} are untouched)",
            path.display(),
            DEFAULT_PATH
        );
    }
    let mut v = serde_json::to_value(Config::default()).expect("config serializes");
    if let serde_json::Value::Object(o) = &mut v {
        o.insert(
            "_readme".into(),
            serde_json::Value::String(
                "The default baseline — authentic values except the deliberate \
                 defaults: prune_owned_jars ON, fog_distance 50 (faithful 20), \
                 hud_transparency off. Generated by mgcarpet; regenerated \
                 automatically when the option schema changes (_version). \
                 Put your overrides in mgcarpet.json with the same structure."
                    .into(),
            ),
        );
        o.insert("_version".into(), serde_json::json!(DEFAULTS_VERSION));
    }
    let text = serde_json::to_string_pretty(&v).expect("config serializes");
    std::fs::write(path, text + "\n").map_err(|e| format!("{}: {e}", path.display()))?;
    println!("config: wrote defaults baseline {}", path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The tracked `mgcarpet.json.defaults` is GENERATED output that
    /// also lives in the repository, so it drifts silently whenever an
    /// option is added or a default changes — and a stale baseline is
    /// merged UNDER the user's overrides, so it really does decide what
    /// people run. Regenerate it (delete it and start the game, or copy
    /// what this test prints) in the same change as the option.
    #[test]
    #[ignore = "regenerates the tracked baseline; run explicitly"]
    fn regenerate_tracked_defaults() {
        let path = Path::new("../../mgcarpet.json");
        ensure_defaults(&defaults_path(path)).expect("write");
    }

    #[test]
    fn tracked_defaults_baseline_is_current() {
        let path = Path::new("../../mgcarpet.json.defaults");
        let Ok(text) = std::fs::read_to_string(path) else {
            return; // not running from the repo
        };
        let tracked: serde_json::Value = serde_json::from_str(&text).expect("defaults parse");
        assert_eq!(
            tracked.get("_version").and_then(|v| v.as_u64()),
            Some(DEFAULTS_VERSION),
            "the tracked defaults baseline is stamped for an older schema"
        );
        let want = serde_json::to_value(Config::default()).expect("config serializes");
        let serde_json::Value::Object(want) = want else {
            unreachable!()
        };
        for (key, value) in want {
            assert_eq!(
                tracked.get(&key),
                Some(&value),
                "tracked defaults disagree with Config::default() at {key}"
            );
        }
    }

    #[test]
    fn stale_defaults_file_regenerates_on_version_bump() {
        let dir = std::env::temp_dir().join(format!("mgc-cfg-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("mgcarpet.json");
        let dpath = defaults_path(&path);
        // An unversioned baseline with a legacy enum value would poison
        // the merge — it must regenerate, not parse.
        std::fs::write(
            &dpath,
            "{\"controls\": {\"preferences\": {\"fly_assistant\": \"auto\"}}}\n",
        )
        .unwrap();
        let cfg = Config::load(&path, false).expect("regenerated baseline loads");
        assert!(!cfg.controls.preferences.fly_assistant.on());
        let text = std::fs::read_to_string(&dpath).unwrap();
        assert!(text.contains("\"_version\""), "regenerated file is stamped");
        std::fs::remove_dir_all(&dir).ok();
    }

    /// The 2026-07-23 crosshair/autoaim split, against the REAL file
    /// shape the menu-persist merge produces: a migrated mgcarpet.json
    /// holds BOTH the stale `render.debug.crosshair` key and the new
    /// `autoaim_hints`. A serde alias would reject that as a
    /// "duplicate field" (both names map to one field), so the stale
    /// key must parse as plain unknown-and-ignored instead.
    #[test]
    fn stale_debug_crosshair_key_is_ignored_not_duplicate() {
        let overlay = serde_json::json!({
            "render": {"debug": {"crosshair": true, "autoaim_hints": true}}
        });
        let cfg: Config = serde_json::from_value(overlay).unwrap();
        assert!(cfg.render.debug.autoaim_hints, "new key honored");
        assert!(
            cfg.render.preference.crosshair,
            "stale debug key does NOT leak into the gameplay crosshair \
             (which simply keeps its default)"
        );
    }

    #[test]
    fn legacy_overlay_values_parse_via_aliases() {
        let overlay = serde_json::json!({
            "controls": {
                "models": {"thrust": "mc1", "altitude": "extended-lift"},
                "preferences": {"fly_assistant": "auto"}
            },
            "render": {"enhancement": {"hud_transparency": "mc1"}},
            "audio": {"subtitles": "auto"}
        });
        let cfg: Config = serde_json::from_value(overlay).unwrap();
        assert_eq!(cfg.controls.models.thrust, ThrustModel::Classic);
        assert_eq!(cfg.controls.models.altitude, AltitudeModel::Enhanced);
        assert!(!cfg.controls.preferences.fly_assistant.on());
        assert!(cfg.render.enhancement.hud_transparency.transparent());
        assert!(cfg.audio.subtitles.on());
    }

    #[test]
    fn defaults_carry_the_documented_deviations() {
        // The documented default deviations, pinned.
        let c = Config::default();
        assert_eq!(c.render.preference.fog_distance, 50, "fog default 50");
        assert!(
            !c.render.enhancement.hud_transparency.transparent(),
            "hud opaque by default"
        );
        assert!(c.controls.preferences.invert_y, "flight-stick polarity");
        assert!(!c.controls.preferences.fly_assistant.on());
        assert!(c.audio.subtitles.on());
        assert!(c.gameplay.enhancement.prune_owned_jars);
        assert_eq!(c.sim.options.game_speed, GameSpeed::Normal);
        // The stops table brackets the default and the faithful value.
        assert!(FOG_STOPS.iter().any(|&(v, _)| v == 20));
        assert!(FOG_STOPS.iter().any(|&(v, _)| v == 50));
    }

    #[test]
    fn game_speed_multipliers_match_retail() {
        // remc1 :41672 (1x/4x/16x), remc2 EF:31800 (1x/4x/8x); slow is
        // our addition.
        assert_eq!(GameSpeed::Normal.multiplier(false), 1.0);
        assert_eq!(GameSpeed::Fast.multiplier(false), 4.0);
        assert_eq!(GameSpeed::VeryFast.multiplier(false), 16.0);
        assert_eq!(GameSpeed::VeryFast.multiplier(true), 8.0);
        assert_eq!(GameSpeed::Slow.multiplier(true), 0.5);
    }
}
